Doc change Ahad
CrossRealms/Splunk-Cyences-App-for-Splunk pull request #240
Opened 2022-12-23 13:42 UTC by mahirchavda

2022-12-23 16:57 UTC, VatsalJagani requested changes

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/data_onboarding/fortigate_vpn.md
> +If your organization uses FortiGate VPN, then the required data can be collected via Fortigate's logs. Refer to the **Data Onboarding > Network Devices > Fortinet FortiGate** section for more informa
Add a proper clickable link.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/data_onboarding/email_o365.md
> +[https://splunkbase.splunk.com/app/3720](https://splunkbase.splunk.com/app/3720)
@mahirchavda - New Office 365 Add-on itself let's us collect the email data. Need to check. Maybe for later, not for now.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/data_onboarding/windows_patch.md
> +## **Windows Patch Data**
Combine this into Windows data onboarding page.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/data_onboarding/windows_eventlog.md
> +## **Windows WinEventLog Data**
Combine this into Windows data onboarding page.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/installation.md
> +| cs_wineventlog_system_timerange | The Lansweeper dashboard searches the WinEventLog:Security (?) data in the last four hours by default to see if the asset collects WinEventLog:Security (?) data. |
Need to fix all the ? (question mark) and TODO in the doc.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/installation.md
> +**Note:** The default value for every macro is: __| search *__ (this would return all results).
Add example filter
for example `NOT user="server-user"`

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/installation.md
> +* Up until Cyences 2.3.0, users have been able to set up an email notification for alerts via Splunk's default method, even with regular Splunk use-cases. This is not always a good idea as some alert
This is part of email topic.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/configuration/installation.md
> +Refer to the **User Guide** > **Cyences Email** section for more information.
Add a proper clickable link.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/index.md
> +The Cyences App for Splunk was designed to allow users complete visibility of their system's security status. It was created with the intention of becoming a seamless piece of the Blue team arsenal f
Need to review it further.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/index.md
> +We're always looking to improve the Cyences app by incorporating new features when possible. The first build came equipped with the Globally Detected Malicious IPs dashboard, which is one of the more
No need to keep description for Globally Detected Malicious IPs on the Home page.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/release_notes/old_release_notes.md
> +    * Network Telemetry
We do not update the old release notes

2022-12-23 16:57 UTC, VatsalJagani commented on docs/release_notes/old_release_notes.md
> +    * Updated `Lansweeper` and `Network Telemetry` dashboard to use `cs_all_vuln` and `cs_all_assets` lookup
We do not update the old release notes

2022-12-23 16:57 UTC, VatsalJagani commented on docs/release_notes/old_release_notes.md
> +    * Network Telemetry
We do not update the old release notes

2022-12-23 16:57 UTC, VatsalJagani commented on docs/release_notes/old_release_notes.md
> +    * Network Telemetry
We do not update the old release notes

2022-12-23 16:57 UTC, VatsalJagani commented on docs/release_notes/release_notes.md
> ---> <TODO> - Let's go through the whole document and document all the functionalities of Cyences on documentation part as well not just the release notes. Also go through previous release notes to ma
@mahirchavda  -below TODOs for us.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/release_notes/release_notes.md
> +    * Users can still view every alert by unchecking the **Hide Not Triggered Alerts** filter.
@mahirchavda  - add note on user to configure emails on both digest email alert and generic critical alert configuration along with the link of that doc page.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/troubleshooting/troubleshooting.md
> ---> <TODO-Mahir> - Is this still valid?
@mahirchavda - need to check.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/user_guide/alerts_dashboards.md
> +There are several security related alerts to choose from and they are all located under the **Settings** drop-down in the navigation bar (Settings > Settings > Searches, Reports and Alerts) of the Cy
Need to bold the text (Settings > Settings > Searches, Reports and Alerts)

2022-12-23 16:57 UTC, VatsalJagani commented on docs/user_guide/alerts_dashboards.md
> +There are several security related alerts to choose from and they are all located under the **Settings** drop-down in the navigation bar (Settings > Settings > Searches, Reports and Alerts) of the Cy
This "Control > Reports" has been changed. @mahirchavda , @adopado

2022-12-23 16:57 UTC, VatsalJagani commented on docs/user_guide/alerts_dashboards.md
> +    * N/A
May be we'll remove this "dashboards" instead of keeing dashboard and mantioning "N/A"

2022-12-23 16:57 UTC, VatsalJagani commented on docs/user_guide/alerts_dashboards.md
> +* CrowdStrike Spotlight Alerts:
No need to specify each separately. Just specify:
* Dashboard panels:
* * New Vulnerability Found Over Time
    * Vulnerabilities 
    * Vulnerability Count By Severity

2022-12-23 16:57 UTC, VatsalJagani commented on docs/user_guide/forensics_dashboard.md
> +The Forensics dashboard is designed to give security engineers insightful information associated with their security investigation. This is mainly a drilldown dashboard from the Overview dashboard, b
Need to review this properly.

2022-12-23 16:57 UTC, VatsalJagani commented on docs/user_guide/cyences_email.md
> +The configuration process for Cyences email alert settings consist of three components.
Need to review this page properly.

2022-12-26 10:17 UTC, mahirchavda commented
Merging this PR. Will incorporate review comment in another branch

2022-12-26 10:28 UTC, crossrealmsint approved these changes

2022-12-26 10:28 UTC, merged

2022-12-26 12:04 UTC, mahirchavda commented on docs/troubleshooting/troubleshooting.md
> ---> <TODO-Mahir> - Is this still valid?
Checked. The issue is still valiad