CY-467: Alert for new vulnerabilities
CrossRealms/Splunk-Cyences-App-for-Splunk pull request #311
Opened 2023-04-25 11:46 UTC by mahirchavda

2023-04-25 13:59 UTC, VatsalJagani commented on cyences_app_for_splunk/default/savedsearches.conf
> +| eval _time=first_found \
Because we are consider reopen as well.

2023-04-27 09:39 UTC, mahirchavda commented on cyences_app_for_splunk/default/savedsearches.conf
> +| eval _time=first_found \
We dont have last_updated information.

2023-04-27 09:46 UTC, VatsalJagani approved these changes

2023-04-27 10:15 UTC, VatsalJagani requested changes

2023-04-27 10:15 UTC, VatsalJagani commented on cyences_app_for_splunk/default/savedsearches.conf
> +action.cyences_notable_event_action.products = Qualys, Tenable
CrowdStrike Spotlight?

2023-04-27 10:20 UTC, VatsalJagani approved these changes

2023-05-04 10:18 UTC, merged