Modified the alert searches to get the related events
CrossRealms/Splunk-Cyences-App-for-Splunk pull request #394
Opened 2023-09-15 14:58 UTC by hardikhdholariya

- Modified the alert searches to get the related events based on Operation field.

2023-09-15 15:31 UTC, VatsalJagani requested changes

2023-09-15 15:31 UTC, VatsalJagani commented on cyences_app_for_splunk/default/savedsearches.conf
> +search = `cs_o365_managementactivity_change("Group")` (Operation!="Add member to group." AND Operation!="Remove member from group.") _index_earliest=-61m@m _index_latest=-1m@m \
We need to ensure we are doing the same change in dashboards as well.

2023-09-15 15:31 UTC, VatsalJagani commented on cyences_app_for_splunk/default/savedsearches.conf
> +search = ((`cs_o365_managementactivity_change("Group")`) OR (`cs_o365_managementactivity_change("GroupMembership")`)) (Operation="Add member to group." OR  Operation="Remove member from group.") _ind
```
((`cs_o365_managementactivity_change("Group")` (Operation="Add member to group." OR Operation="Remove member from group.")) OR `cs_o365_managementactivity_change("GroupMembership")` )
```

bracket changes.

2023-09-19 11:09 UTC, mahirchavda approved these changes

2023-09-19 11:26 UTC, VatsalJagani approved these changes

2023-09-19 12:43 UTC, merged