Update sophos alerts
CrossRealms/Splunk-Cyences-App-for-Splunk pull request #425
Opened 2023-10-20 16:58 UTC by roaaattalla

2023-10-20 17:02 UTC, roaaattalla commented on cyences_app_for_splunk/default/data/ui/views/cs_sophos_reports.xml
> +          <query> cs_sophos` sourcetype="sophos_events" type="Event::Endpoint::CoreDetection" $tkn_host$ $tkn_dhost$ $tkn_user$
Already changed

2023-10-23 05:04 UTC, hardikhdholariya requested changes

2023-10-23 05:04 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +action.cyences_notable_event_action.system_compromised_drilldown = `cs_sophos` location=$row.location$
Add the sourcetype="sophos_events" filter

2023-10-23 05:04 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +action.cyences_notable_event_action.system_compromised_drilldown = `cs_sophos` location=$row.location$
Add the sourcetype="sophos_events" filter

2023-10-23 05:04 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +action.cyences_notable_event_action.system_compromised_drilldown = `cs_sophos` location=$row.location$
Add the sourcetype="sophos_events" filter

2023-10-23 05:04 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +`cs_sophos` sourcetype="sophos_events" type IN ("Event::Endpoint::Threat::CleanupFailed", "Event::Endpoint::CoreCleanFailed", "Event::Endpoint::CoreHmpaCleanFailed", "Event::Endpoint::CoreSystemClean
**search =** key is missing.

2023-10-23 05:04 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +| `cs_sophos_failed_to_cleanup_threat_filter` \
Remove the forward slash (\) at the end.

2023-10-23 05:04 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +action.cyences_notable_event_action.contributing_events = `cs_sophos` "sophos_events" type IN ("Event::Endpoint::Threat::CleanupFailed", "Event::Endpoint::CoreCleanFailed", "Event::Endpoint::CoreHmpa
Add the **sourcetype=**"sophos_events" filter

2023-10-23 05:04 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +action.cyences_notable_event_action.system_compromised_drilldown = `cs_sophos` location=$row.location$
Add the sourcetype="sophos_events" filter

2023-10-23 12:33 UTC, hardikhdholariya approved these changes

2023-10-23 12:40 UTC, merged