"Failed Unusual log in for (O365, AWS, GWS)
CrossRealms/Splunk-Cyences-App-for-Splunk pull request #445
Opened 2023-11-10 18:19 UTC by roaaattalla

2023-11-10 18:22 UTC, roaaattalla commented on cyences_app_for_splunk/default/savedsearches.conf
> +    | fields _time sourcetype userPrincipalName ipAddress id LogonError appDisplayName status.failureReason clientAppUsed conditionalAccessStatus isInteractive deviceDetail.* org_country org_region o
For (status.failReason) when I run the query it doesn't show data .. I tried several things to make it work but it doesn't show any data so can you please check the query maybe you can recognize if I'm missing something

2023-11-17 15:37 UTC, hardikhdholariya requested changes

2023-11-24 14:42 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +| fields - Id, sourcetype, lat, lon, deviceDetail.deviceId, \
remove unwanted command from the end of line.

2023-12-04 17:09 UTC, hardikhdholariya requested changes

2023-12-04 17:09 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +search = `cs_gws_login_events` "event.name"="login_failure" `cs_public_ips(ipAddress)` \
Add **_index_earliest=-61m@m _index_latest=-1m@m** in the search

2023-12-04 17:09 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/savedsearches.conf
> +| eval cyences_severity = case(percentage_login_from_country==0 or or is_privileged_user=="Yes", "critical", true(), "medium") \
remove **or**, it's typed twice in sequence.

2023-12-04 17:53 UTC, roaaattalla commented on cyences_app_for_splunk/default/savedsearches.conf
> +action.cyences_notable_event_action.system_compromised_drilldown = `cs_gws_login_events` "event.name"="login_failure"`cs_public_ips(ipAddress)` user=$row.user$ | iplocation ipAddress
Done no errors

2023-12-04 18:08 UTC, hardikhdholariya approved these changes

2023-12-05 09:34 UTC, merged