Moved the splunklib to the lib folder
CrossRealms/Splunk-Cyences-App-for-Splunk pull request #636
Opened 2024-09-18 14:36 UTC by hardikhdholariya

2024-09-18 14:38 UTC, VatsalJagani requested changes
Need to update github action file with **splunk_python_sdk_install_path** parameter

2024-09-19 08:38 UTC, mahirchavda approved these changes

2024-09-23 10:34 UTC, VatsalJagani requested changes

2024-09-23 10:34 UTC, VatsalJagani commented on .github/workflows/on_master.yml
> +          splunk_python_sdk_install_path: "lib"
Use v4.1 instead of v4

2024-09-23 15:18 UTC, VatsalJagani approved these changes

2024-09-23 15:52 UTC, merged