Integrate blockshield ai
CrossRealms/Splunk-Cyences-App-for-Splunk pull request #653
Opened 2024-10-09 13:33 UTC by hardikhdholariya

2024-10-09 14:33 UTC, VatsalJagani requested changes

2024-10-09 14:33 UTC, VatsalJagani commented on cyences_app_for_splunk/default/commands.conf
> +[cyencesipinfo]
Same as previous comment of it name it as blockshieldipinfo

2024-10-10 05:08 UTC, hardikhdholariya commented on cyences_app_for_splunk/default/data/ui/views/cs_asset_intelligence.xml
> +          <query>| makeresults count=1 | eval ip=$tkn_filter_ip_only$ | cyencesipinfo fieldname="ip" | fields - _time | table ip, *
input with wildcard is not supported from API end. if someone enters then it will show the error message on top right for any errors.

2024-10-10 05:25 UTC, VatsalJagani approved these changes

2024-10-10 05:45 UTC, merged